- name: application installs
  include: apps.yml 

- name: configuration
  include: configuration.yml

#- name: dotfiles
#  include: dotfiles.yml

- name: Vim SPF13 configuration
  include: vim_spf13.yml 

- name: Install Python modules
  pip:
    name: setuptools_scm,virtualenv,readline
